import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Navbar, Footer } from "./_components";
import { inter } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
